const allowedTagValues = [
  "Farming",
  "Wildlife",
  "Business",
  "Climate",
  "Community",
  "Crisis",
  "Culture",
  "Development",
  "Economy",
  "Energy",
  "Environment",
  "Food",
  "Healthcare",
  "Housing",
  "HumanRights",
  "Innovation",
  "Medical",
  "Security",
  "Sports",
  "Technology",
  "Women",
  "Youth",
  "Rewilding",
  "ElderCare",
  "Education",
  "CleanWater",
];

exports.allowedTagValues = allowedTagValues;
