// not currently synched with prisma - might be impossible
export const TagValues = [
  "HungerAndFoodSecurity",
  "HomelessnessAndHousing",
  "DisasterReliefAndRecovery",
  "ChildWelfare",
  "ElderlyCare",
  "EducationAndLiteracy",
  "HealthcareAndMedicalResearch",
  "MentalHealthSupport",
  "CancerResearchAndSupport",
  "HIVAIDSPreventionAndSupport",
  "HeartDiseaseResearch",
  "DiabetesResearchAndSupport",
  "EnvironmentalConservation",
  "WildlifePreservation",
  "MarineConservation",
  "ClimateChangeMitigation",
  "SustainableDevelopment",
  "CleanWaterAndSanitation",
  "RenewableEnergyInitiatives",
  "AnimalWelfareAndRights",
  "DomesticViolencePreventionAndSupport",
  "HumanTraffickingPreventionAndAid",
  "RefugeeAndImmigrantSupport",
  "VeteransSupport",
  "DisabilitiesSupportAndAdvocacy",
  "MentalDisabilitiesSupport",
  "PhysicalDisabilitiesSupport",
  "ArtsAndCulture",
  "HistoricalPreservationAndRestoration",
  "ScientificResearchAndInnovation",
  "UrbanDevelopmentAndPlanning",
  "CommunityBuildingAndSocialWork",
  "PovertyAlleviation",
  "MicrofinanceAndEconomicEmpowerment",
  "GirlsAndWomensRights",
  "LGBTQPlusRightsAndSupport",
  "RacialAndEthnicEquality",
  "ReligiousAndSpiritualSupport",
  "PeaceAndConflictResolution",
  "LegalAidAndAdvocacy",
  "SubstanceAbusePreventionAndTreatment",
  "EducationForUnderprivilegedChildren",
  "YouthDevelopmentAndLeadership",
  "GlobalHealthInitiatives",
  "OrphanageSupportAndAdoptionServices",
  "DementiaAndAlzheimersSupport",
  "OrganAndTissueDonationAwareness",
  "CulturalExchangeAndUnderstanding",
  "DigitalInclusionAndInternetAccess",
  "HumanRightsAdvocacy",
  "HealthServices",
  "Technology",
  "CleanWater",
  "EconomicEmpowerment",
];
export const TagValuesObj = {
  HungerAndFoodSecurity: "HungerAndFoodSecurity",
  HomelessnessAndHousing: "HomelessnessAndHousing",
  DisasterReliefAndRecovery: "DisasterReliefAndRecovery",
  ChildWelfare: "ChildWelfare",
  ElderlyCare: "ElderlyCare",
  EducationAndLiteracy: "EducationAndLiteracy",
  HealthcareAndMedicalResearch: "HealthcareAndMedicalResearch",
  MentalHealthSupport: "MentalHealthSupport",
  CancerResearchAndSupport: "CancerResearchAndSupport",
  HIVAIDSPreventionAndSupport: "HIVAIDSPreventionAndSupport",
  HeartDiseaseResearch: "HeartDiseaseResearch",
  DiabetesResearchAndSupport: "DiabetesResearchAndSupport",
  EnvironmentalConservation: "EnvironmentalConservation",
  WildlifePreservation: "WildlifePreservation",
  MarineConservation: "MarineConservation",
  ClimateChangeMitigation: "ClimateChangeMitigation",
  SustainableDevelopment: "SustainableDevelopment",
  CleanWaterAndSanitation: "CleanWaterAndSanitation",
  RenewableEnergyInitiatives: "RenewableEnergyInitiatives",
  AnimalWelfareAndRights: "AnimalWelfareAndRights",
  DomesticViolencePreventionAndSupport: "DomesticViolencePreventionAndSupport",
  HumanTraffickingPreventionAndAid: "HumanTraffickingPreventionAndAid",
  RefugeeAndImmigrantSupport: "RefugeeAndImmigrantSupport",
  VeteransSupport: "VeteransSupport",
  DisabilitiesSupportAndAdvocacy: "DisabilitiesSupportAndAdvocacy",
  MentalDisabilitiesSupport: "MentalDisabilitiesSupport",
  PhysicalDisabilitiesSupport: "PhysicalDisabilitiesSupport",
  ArtsAndCulture: "ArtsAndCulture",
  HistoricalPreservationAndRestoration: "HistoricalPreservationAndRestoration",
  ScientificResearchAndInnovation: "ScientificResearchAndInnovation",
  UrbanDevelopmentAndPlanning: "UrbanDevelopmentAndPlanning",
  CommunityBuildingAndSocialWork: "CommunityBuildingAndSocialWork",
  PovertyAlleviation: "PovertyAlleviation",
  MicrofinanceAndEconomicEmpowerment: "MicrofinanceAndEconomicEmpowerment",
  GirlsAndWomensRights: "GirlsAndWomensRights",
  LGBTQPlusRightsAndSupport: "LGBTQPlusRightsAndSupport",
  RacialAndEthnicEquality: "RacialAndEthnicEquality",
  ReligiousAndSpiritualSupport: "ReligiousAndSpiritualSupport",
  PeaceAndConflictResolution: "PeaceAndConflictResolution",
  LegalAidAndAdvocacy: "LegalAidAndAdvocacy",
  SubstanceAbusePreventionAndTreatment: "SubstanceAbusePreventionAndTreatment",
  EducationForUnderprivilegedChildren: "EducationForUnderprivilegedChildren",
  YouthDevelopmentAndLeadership: "YouthDevelopmentAndLeadership",
  GlobalHealthInitiatives: "GlobalHealthInitiatives",
  OrphanageSupportAndAdoptionServices: "OrphanageSupportAndAdoptionServices",
  DementiaAndAlzheimersSupport: "DementiaAndAlzheimersSupport",
  OrganAndTissueDonationAwareness: "OrganAndTissueDonationAwareness",
  CulturalExchangeAndUnderstanding: "CulturalExchangeAndUnderstanding",
  DigitalInclusionAndInternetAccess: "DigitalInclusionAndInternetAccess",
  HumanRightsAdvocacy: "HumanRightsAdvocacy",
  HealthServices: "HealthServices",
  Technology: "Technology",
  CleanWater: "CleanWater",
  EconomicEmpowerment: "EconomicEmpowerment",
};
