// not currently synched with prisma - might be impossible
export const TagValues = [
  "HungerAndFoodSecurity",
  "HomelessnessAndHousing",
  "DisasterReliefAndRecovery",
  "ChildWelfare",
  "ElderlyCare",
  "EducationAndLiteracy",
  "HealthcareAndMedicalResearch",
  "MentalHealthSupport",
  "CancerResearchAndSupport",
  "HIVAIDSPreventionAndSupport",
  "HeartDiseaseResearch",
  "DiabetesResearchAndSupport",
  "EnvironmentalConservation",
  "WildlifePreservation",
  "MarineConservation",
  "ClimateChangeMitigation",
  "SustainableDevelopment",
  "CleanWaterAndSanitation",
  "RenewableEnergyInitiatives",
  "AnimalWelfareAndRights",
  "DomesticViolencePreventionAndSupport",
  "HumanTraffickingPreventionAndAid",
  "RefugeeAndImmigrantSupport",
  "VeteransSupport",
  "DisabilitiesSupportAndAdvocacy",
  "MentalDisabilitiesSupport",
  "PhysicalDisabilitiesSupport",
  "ArtsAndCulture",
  "HistoricalPreservationAndRestoration",
  "ScientificResearchAndInnovation",
  "UrbanDevelopmentAndPlanning",
  "CommunityBuildingAndSocialWork",
  "PovertyAlleviation",
  "MicrofinanceAndEconomicEmpowerment",
  "GirlsAndWomensRights",
  "LGBTQPlusRightsAndSupport",
  "RacialAndEthnicEquality",
  "ReligiousAndSpiritualSupport",
  "PeaceAndConflictResolution",
  "LegalAidAndAdvocacy",
  "SubstanceAbusePreventionAndTreatment",
  "EducationForUnderprivilegedChildren",
  "YouthDevelopmentAndLeadership",
  "GlobalHealthInitiatives",
  "OrphanageSupportAndAdoptionServices",
  "DementiaAndAlzheimersSupport",
  "OrganAndTissueDonationAwareness",
  "CulturalExchangeAndUnderstanding",
  "DigitalInclusionAndInternetAccess",
  "HumanRightsAdvocacy",
  "HealthServices",
  "Technology",
  "CleanWater",
  "EconomicEmpowerment",
];
export const TagValuesObj = {
  HungerAndFoodSecurity: "Hunger And Food Security",
  HomelessnessAndHousing: "Homelessness And Housing",
  DisasterReliefAndRecovery: "Disaster Relief And Recovery",
  ChildWelfare: "Child Welfare",
  ElderlyCare: "Elderly Care",
  EducationAndLiteracy: "Education And Literacy",
  HealthcareAndMedicalResearch: "Healthcare And Medical Research",
  MentalHealthSupport: "Mental Health Support",
  CancerResearchAndSupport: "Cancer Research And Support",
  HIVAIDSPreventionAndSupport: "HIV AIDS Prevention And Support",
  HeartDiseaseResearch: "Heart Disease Research",
  DiabetesResearchAndSupport: "Diabetes Research And Support",
  EnvironmentalConservation: "Environmental Conservation",
  WildlifePreservation: "Wildlife Preservation",
  MarineConservation: "Marine Conservation",
  ClimateChangeMitigation: "Climate Change Mitigation",
  SustainableDevelopment: "Sustainable Development",
  CleanWaterAndSanitation: "Clean Water And Sanitation",
  RenewableEnergyInitiatives: "Renewable Energy Initiatives",
  AnimalWelfareAndRights: "Animal Welfare And Rights",
  DomesticViolencePreventionAndSupport:
    "Domestic Violence Prevention And Support",
  HumanTraffickingPreventionAndAid: "Human Trafficking Prevention And Aid",
  RefugeeAndImmigrantSupport: "Refugee And Immigrant Support",
  VeteransSupport: "Veterans Support",
  DisabilitiesSupportAndAdvocacy: "Disabilities Support And Advocacy",
  MentalDisabilitiesSupport: "Mental Disabilities Support",
  PhysicalDisabilitiesSupport: "Physical Disabilities Support",
  ArtsAndCulture: "Arts And Culture",
  HistoricalPreservationAndRestoration:
    "Historical Preservation And Restoration",
  ScientificResearchAndInnovation: "Scientific Research And Innovation",
  UrbanDevelopmentAndPlanning: "Urban Development And Planning",
  CommunityBuildingAndSocialWork: "Community Building And Social Work",
  PovertyAlleviation: "Poverty Alleviation",
  MicrofinanceAndEconomicEmpowerment: "Microfinance And Economic Empowerment",
  GirlsAndWomensRights: "Girls And Womens Rights",
  LGBTQPlusRightsAndSupport: "LGBTQ Plus Rights And Support",
  RacialAndEthnicEquality: "Racial And Ethnic Equality",
  ReligiousAndSpiritualSupport: "Religious And Spiritual Support",
  PeaceAndConflictResolution: "Peace And Conflict Resolution",
  LegalAidAndAdvocacy: "Legal Aid And Advocacy",
  SubstanceAbusePreventionAndTreatment:
    "Substance Abuse Prevention And Treatment",
  EducationForUnderprivilegedChildren: "Education For Underprivileged Children",
  YouthDevelopmentAndLeadership: "Youth Development And Leadership",
  GlobalHealthInitiatives: "Global Health Initiatives",
  OrphanageSupportAndAdoptionServices:
    "Orphanage Support And Adoption Services",
  DementiaAndAlzheimersSupport: "Dementia And Alzheimers Support",
  OrganAndTissueDonationAwareness: "Organ And Tissue Donation Awareness",
  CulturalExchangeAndUnderstanding: "Cultural Exchange And Understanding",
  DigitalInclusionAndInternetAccess: "Digital Inclusion And Internet Access",
  HumanRightsAdvocacy: "Human Rights Advocacy",
  HealthServices: "Health Services",
  Technology: "Technology",
  CleanWater: "Clean Water",
  EconomicEmpowerment: "Economic Empowerment",
};
