// not currently synched with prisma - might be impossible
export const TagValues = [
  "HungerAndFoodSecurity",
  "HomelessnessAndHousing",
  "DisasterReliefAndRecovery",
  "ChildWelfare",
  "ElderlyCare",
  "EducationAndLiteracy",
  "HealthcareAndMedicalResearch",
  "MentalHealthSupport",
  "CancerResearchAndSupport",
  "HIVAIDSPreventionAndSupport",
  "HeartDiseaseResearch",
  "DiabetesResearchAndSupport",
  "EnvironmentalConservation",
  "WildlifePreservation",
  "MarineConservation",
  "ClimateChangeMitigation",
  "SustainableDevelopment",
  "CleanWaterAndSanitation",
  "RenewableEnergyInitiatives",
  "AnimalWelfareAndRights",
  "DomesticViolencePreventionAndSupport",
  "HumanTraffickingPreventionAndAid",
  "RefugeeAndImmigrantSupport",
  "VeteransSupport",
  "DisabilitiesSupportAndAdvocacy",
  "MentalDisabilitiesSupport",
  "PhysicalDisabilitiesSupport",
  "ArtsAndCulture",
  "HistoricalPreservationAndRestoration",
  "ScientificResearchAndInnovation",
  "UrbanDevelopmentAndPlanning",
  "CommunityBuildingAndSocialWork",
  "PovertyAlleviation",
  "MicrofinanceAndEconomicEmpowerment",
  "GirlsAndWomensRights",
  "LGBTQPlusRightsAndSupport",
  "RacialAndEthnicEquality",
  "ReligiousAndSpiritualSupport",
  "PeaceAndConflictResolution",
  "LegalAidAndAdvocacy",
  "SubstanceAbusePreventionAndTreatment",
  "EducationForUnderprivilegedChildren",
  "YouthDevelopmentAndLeadership",
  "GlobalHealthInitiatives",
  "OrphanageSupportAndAdoptionServices",
  "DementiaAndAlzheimersSupport",
  "OrganAndTissueDonationAwareness",
  "CulturalExchangeAndUnderstanding",
  "DigitalInclusionAndInternetAccess",
  "HumanRightsAdvocacy",
  "HealthServices",
  "Technology",
  "CleanWater",
  "EconomicEmpowerment",
];
export const TagValuesObj = {
  Farming: "Farming",
  Wildlife: "Wildlife",
  Business: "Business",
  Climate: "Climate",
  Community: "Community",
  Crisis: "Crisis",
  Culture: "Culture",
  Development: "Development",
  Economy: "Economy",
  Energy: "Energy",
  Environment: "Environment",
  Food: "Food",
  Healthcare: "Healthcare",
  Housing: "Housing",
  HumanRights: "Human Rights",
  Innovation: "Innovation",
  Medical: "Medical",
  Security: "Security",
  Sports: "Sports",
  Technology: "Technology",
  Women: "Women",
  Youth: "Youth",
  Rewilding: "Rewilding",
  ElderCare: "Elder Care",
  Education: "Education",
  CleanWater: "Clean Water",
};
